### ISSUE TITLE
Remove parameter of meshconfig for sidecar-initializer

### ISSUE THREAD

**Issue by gyliu513** [istio/pilot#1189]
The sidecar-initializer can also enable end user setting the meshconfig via the start up parameter, I think that we can remove this parameter now as we already support this parameter in https://github.com/istio/pilot/blob/master/test/integration/testdata/initializer-configmap.yaml.tmpl#L19 

```
rootCmd.PersistentFlags().StringVar(&flags.meshconfig, "meshconfig", "/etc/istio/config/mesh",
		"File name for Istio mesh configuration")
```

/cc @ayj

**Comment by ayj** [comment]
`meshconfig` and `MeshConfigMapName` are used for different purposes.

* `meshconfig` is used by the initializer deployment for mesh-level configuration
* `MeshConfigMapName` is used to mount the configuration in the sidecar itself.

Initializer could programatically access `MeshConfigMapName` through k8s go-client instead of volume mount, but you'd need to add retry-logic (e.g. `wait.Poll`) to handle start-up (when deployment is created before ConfigMap) and hot reloads (and proxy mesh configuration changes). Using the existing volume mount method handles the first case and the latter can be easily addressed with ionotify.

**Comment by kyessenov** [comment]
Fyi, it's probably time to switch to a dedicated CRD for the mesh config since it causes problems with multi-namespace deployment. There'll be one main config CRD in pilot namespace consumed by pilot service. Agents will go back to using flags for non-critical parameters (e.g. restart durations). Can we use initializer config to set those flags literally (as a string of args)?

**Comment by gyliu513** [comment]
Thanks @ayj so how can `meshconfig` handle hot reloads? I mean if it is updated during runtime, I may need to restart initializer?

**Comment by ayj** [comment]
You'll need to restart the initializer right now. It could be updated to use https://github.com/fsnotify/fsnotify to watch and reload the ConfigMap to avoid the restart.

**Comment by gyliu513** [comment]
Got it, thanks @ayj
