### ISSUE TITLE
Ingress controller should reside in installation namespace

### ISSUE THREAD

**Issue by kyessenov** [istio/pilot#1273]
Current installation templates put ingress proxies in the application namespace (cc @andraxylia ). 
I recommend we put all ingress and egress proxies into the installation namespace, as they are managed by istio and handle cluster-wide ingresses, rather than having independent identical proxies in each application namespace.

@rshriram @linsun @costinm @louiscryan

**Comment by rshriram** [comment]
cc @dcberg

**Comment by andraxylia** [comment]
This incorrect, the ingress and egress controller are in the istio-system namespace.

**Comment by andraxylia** [comment]
Just the actual ingress resource is in the app namespace, since it is controlled by the developer.

Please check the design doc for cluster-wide, and close this issue:
https://docs.google.com/document/d/1Of0SUxNLzVQyBO9xx2fEKsN4vwyp72csbWd-8xjeLS0/edit

**Comment by costinm** [comment]
So the services run in istio-system, but resources must be in app namespace, for security reasons.

We need to minimize users crossing namespace boundaries - ideally no service account in user namespace should have permissions on the istio-system namespace.

**Comment by kyessenov** [comment]
Please fix the code:
https://github.com/istio/pilot/blob/master/test/integration/infra.go#L216

**Comment by andraxylia** [comment]
So this issue is about changing the pilot e2e tests, I see. Sure, it can be done differently. There were issues with running pilot e2e tests in a shared cluster, so this was a way to test cluster-wide without causing interference among various concurrent runs.

The actual templates in istio/istio are like this, and ingress is in the installation ns:
https://github.com/istio/istio/blob/master/install/kubernetes/istio-cluster-wide.yaml#L568

I am adding cluster-wide e2e tests in istio/istio, which need to be run using the isolated cluster infrastructure that only became available yesterday.
